# Generated by Django 5.2.3 on 2025-07-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_attendance_ip_address_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='ip_address',
        ),
    ]
