# Generated by Django 5.2.3 on 2025-07-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_attendance_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
