# Generated by Django 5.2.3 on 2025-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_attendance_ip_address_alter_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
