# Generated by Django 5.2.3 on 2025-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_attendance_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='longitude',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
