# Generated by Django 5.2.3 on 2025-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
