# Generated by Django 5.2.3 on 2025-07-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_attendance_latitude_attendance_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attname',
            new_name='name',
        ),
    ]
