# Generated by Django 5.2.3 on 2025-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_attendance_options_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.EmailField(blank=True, default='no-reply@venus.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(blank=True, default='no-reply@venus.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='qr_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=20),
        ),
    ]
