# Generated by Django 5.2.3 on 2025-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile_address_profile_gender_alter_profile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='qr_code',
            field=models.TextField(),
        ),
    ]
